Display all Expense category
holuborhee/trackbill pull request #5
Opened 2022-01-25 23:17 UTC by timtech-wiz

2022-01-25 23:18 UTC, timtech-wiz commented
![Screenshot (13)](https://user-images.githubusercontent.com/60903808/151075956-7d13b325-9912-47e6-a190-e586502bba6c.png)

2022-01-26 20:26 UTC, holuborhee requested changes
Kindly note the requested changes. 

Also, check out this section of the doc https://v3.vuejs.org/style-guide/#order-of-words-in-component-names-strongly-recommended. Read the detailed explanation for an understanding of the recommendation when it comes to putting components in folders. I am still not comfortable with your folder structure. You should have two folders `components` and `views`. Pages should be inside the views folder, components that aren't pages should be in the components folder and there should be no subdirectory.

2022-01-26 20:26 UTC, holuborhee commented on login.html
> +
what's the use of these codes you commented out? Looks like the whole file is not even needed why do we have it here?

2022-01-26 20:26 UTC, holuborhee commented on src/App.vue
> +      <the-header></the-header>
This is meant to be written as `<TheHeader/>`. Kindly refer to the following links

https://v3.vuejs.org/style-guide/#self-closing-components-strongly-recommended
https://v3.vuejs.org/style-guide/#component-name-casing-in-templates-strongly-recommended
```suggestion
      <TheHeader/>
```

Correct all other such instances where you repeated the same approach

2022-01-27 11:28 UTC, merged