create single expense page and modal
holuborhee/trackbill pull request #6
Opened 2022-02-09 12:48 UTC by timtech-wiz

2022-02-09 12:51 UTC, timtech-wiz commented
![Screenshot (17)](https://user-images.githubusercontent.com/60903808/153204669-658131bf-bee8-42b5-8589-0115c3d74948.png)
![Screenshot (18)](https://user-images.githubusercontent.com/60903808/153204673-b98114a6-73fd-4b06-bc71-7a71c7058e9c.png)

2022-02-14 00:56 UTC, holuborhee requested changes

2022-02-14 00:56 UTC, holuborhee commented on src/App.vue
> +import WishListModal from './components/WishListModal.vue'
why this import here?

2022-02-14 00:56 UTC, holuborhee commented on src/views/ExpenseCategory.vue
> +                                <a href="single-expense-category" class="rounded px-3 py-2 mr-2 bg-orange-500 hover:bg-orange-700">View</a>
why use `<a>` tag instead of `<router-link>` component

2022-02-14 00:56 UTC, holuborhee commented on src/main.js
> +import { createApp, VueElement } from 'vue'
you imported vue element here but you are not using it

2022-02-14 00:56 UTC, holuborhee commented on src/components/WishListModal.vue
> +      </button>
the create wishlist cannot be here, it should be in the `SingleExpenseCategory.vue` file

2022-02-22 16:18 UTC, holuborhee commented on src/views/SingleExpenseCategory.vue
> +      },
This is a good use case for computed instead of methods. Read about computed here https://vuejs.org/guide/essentials/computed.html

2022-02-22 22:13 UTC, holuborhee approved these changes

2022-02-22 22:14 UTC, merged