Create auth page
holuborhee/trackbill pull request #8
Opened 2022-03-18 11:34 UTC by timtech-wiz

2022-03-18 11:36 UTC, timtech-wiz commented
![Screenshot (53)](https://user-images.githubusercontent.com/60903808/158996335-f800dcb4-95af-4f13-9a56-7442f5c6e4cf.png)

2022-05-30 10:45 UTC, holuborhee requested changes
Kindly implement the changes, also change your PR name to "Landing Page Design"

2022-05-30 10:45 UTC, holuborhee commented on src/routes.js
> +                      name:'FrontPage'
This should be rather named `Landing`, not sure if there is a point to putting `page` as a suffix to anyone, they are all pages since they live in the view file and are routes.

2022-05-30 10:45 UTC, holuborhee commented on src/routes.js
> +                      name:'login-code'
Are using kebab case or camel case for route names?

2022-05-30 10:45 UTC, holuborhee commented on src/routes.js
> +import LoginCode from "./views/LoginCode.vue";
You should not have anything login code in this PR

2022-05-30 10:45 UTC, holuborhee commented on tailwind.config.js
> +      backgroundImage: {
This is more of a one-off background image https://tailwindcss.com/docs/background-image#arbitrary-values

2022-06-01 22:47 UTC, timtech-wiz commented on src/routes.js
> +                      name:'login-code'
camel case sir

2022-06-08 23:48 UTC, holuborhee approved these changes

2022-06-08 23:48 UTC, merged